name: cellar
description: Project Cellar

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  multi_image_picker: ^4.7.14
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_storage: ^10.2.4
  firebase_auth: ^3.3.4
  firebase_crashlytics: ^2.4.4
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.2.1
  apple_sign_in: ^0.1.0
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  permission_handler: 8.3.0
  url_launcher: ^6.0.17
  lottie: ^1.2.1
  animations: ^2.0.2
  table_calendar: ^3.0.3
  charts_flutter: ^0.12.0
  package_info: ^2.0.2
  pub_semver: ^2.1.0
  fluttertoast: ^8.0.8

  flutter_launcher_icons: ^0.9.2
  rename: 2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/lottie/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/upload-icon.png
    - assets/images/apple-logo.png
    - assets/images/google-logo.png
    - assets/lottie/loading.json
