name: cellar
description: Project Cellar

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  image: ^3.0.2
  image_picker: ^0.8.6
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.8
  firebase_storage: ^11.0.9
  firebase_auth: ^4.2.3
  firebase_crashlytics: ^3.0.8
  cloud_firestore: ^4.3.0
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.7
  lottie: ^2.1.0
  animations: ^2.0.7
  table_calendar: ^3.0.8
  fl_chart: ^0.61.0
  package_info_plus: ^3.0.2
  pub_semver: ^2.1.3
  fluttertoast: ^8.1.2

  flutter_launcher_icons: ^0.11.0
  rename: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/lottie/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/upload-icon.png
    - assets/images/apple-logo.png
    - assets/images/google-logo.png
    - assets/lottie/loading.json
